import { ReactNode } from "react";
import { Inter } from 'next/font/google'
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aniket Dhiman',
  description: 'Generated by Aniket Dhiman',
}

interface MyComponentProps {
  children: ReactNode;
}

export default function RootLayout({ children }:MyComponentProps) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
